app = "ksa-dashboard"

[build]
  builder = "heroku/buildpacks:20"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

[machines]
  size = "shared-cpu-1x"  # smallest allowed free/shared size
