app = "ksa-dashboard"

[build]
  builder = "heroku/buildpacks:20"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

[machines]
  size = "shared-1x"   # smallest free-tier size (1 CPU, 1 GB RAM)
  count = 1
