import express from "express";
import { createServer } from "http";
import { Server } from "socket.io";

const app = express();
const httpServer = createServer(app);
const io = new Server(httpServer);

app.use(express.static("public"));

// USER CONFIG (slugs and autogenerated passwords)
const users = {
  "384927": { name: "Selmy", password: "P$8rVq2xL!a" },
  "590213": { name: "Basmalah", password: "u9F&3bK#tQ1" },
  "718405": { name: "Eman", password: "Zp7@vR5mS2y" },
  "062491": { name: "Maya", password: "xE4$k9N!pT8" },
  "246801": { name: "Rana", password: "M#6tQ2zY7uV" },
  "975310": { name: "Yara", password: "s8W&1pL#cF4" },
  "130579": { name: "Youssef", password: "B2!rN7qH$k9" },
  "483020": { name: "newbie", password: "g6Z#x3T&pL0" }
};

// IN-MEMORY DATA
const statusData = {};
Object.keys(users).forEach(slug => {
  statusData[slug] = {
    active: false,
    lastUpdate: Date.now(),
    lastActive: null,
    activeSeconds: 0,
    dailyLogins: 0
  };
});

// ROUTES (serve pages)
app.get("/u/:slug", (req, res) => {
  res.sendFile(process.cwd() + "/public/user.html");
});

app.get("/dashboard", (req, res) => {
  res.sendFile(process.cwd() + "/public/dashboard.html");
});

// SOCKET.IO - real-time events
io.on("connection", socket => {
  socket.emit("status-update", statusData);

  socket.on("login-user", ({ slug, password }) => {
    if (!users[slug]) {
      socket.emit("login-result", { success: false, msg: "Invalid URL" });
      return;
    }
    if (users[slug].password !== password) {
      socket.emit("login-result", { success: false, msg: "Wrong password" });
      return;
    }
    statusData[slug].dailyLogins++;
    statusData[slug].lastUpdate = Date.now();
    socket.emit("login-result", { success: true, name: users[slug].name });
    io.emit("status-update", statusData);
  });

  socket.on("toggle-status", ({ slug, state }) => {
    if (!statusData[slug]) return;
    statusData[slug].active = !!state;
    statusData[slug].lastUpdate = Date.now();
    if (state) {
      statusData[slug].lastActive = Date.now();
    }
    io.emit("status-update", statusData);
  });

  socket.on("heartbeat", slug => {
    if (!statusData[slug]) return;
    if (statusData[slug].active) {
      statusData[slug].activeSeconds += 1;
      statusData[slug].lastActive = Date.now();
    }
  });
});

// Listen on correct port
const PORT = process.env.PORT || 3000;
httpServer.listen(PORT, "0.0.0.0", () => {
  console.log("Server running on port", PORT);
});
